# This is a basic workflow to help you get started with Actions

name: Build and Deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: npm install, build
        run: |
          npm install
          npm run build

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist

      - name: checkout to branch gh-pages
        uses: actions/checkout@v2
        with:
          ref: gh-pages

      - name: Download dist
        uses: actions/download-artifact@v2
        with:
          name: dist
          
      - name: commit and push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          mv ./dist ./docs
          git add ./docs
          git commit -m "Update distribution"
          git push

      
        
